Create 20240506-CGN-NuoveAgevolazioni.json
pagopa/io-bulk-message pull request #28
Opened 2024-05-06 10:59 UTC by Hantex9

2024-05-06 18:12 UTC, angelo-fiorillo requested changes
Ci sono diversi errori, il codice corretto è il seguente:
```
  "content": {
    "subject": "Carta Giovani Nazionale: le novità del mese di Maggio",
    "markdown": "---\nit:\n    cta_1: \n        text: \"Vai a CGN\"\n        action: \"ioit://CGN_DETAILS\"\nen:\n    cta_1: \n        text: \"See your CGN\"\n        action: \"ioit://CGN_DETAILS\"\n---\nLo sai che su Carta Giovani Nazionale ci sono delle nuove opportunità che possono interessarti?\n\n📌 Sedute di psicoterapia, corsi di francese, ingressi a musei e parco divertimenti, servizi e utenze per la casa\nScopri le novità del mese, le riconosci dal simbolo 🔔\n\nSeguici sui social per avere tutti i dettagli  \nInstagram - [Le novità del mese](https://www.instagram.com/p/C6f8KwSo4xG/?igsh=bDRrbXVhb2E2ajlk)  \nFacebook - [Le novità del mese](https://www.facebook.com/share/p/aDtKfRHYjMFmaUjh/?mibextid=WC7FNe)"
    }
```
Potete sistemarlo incollandoci esattamente questo e avvertirmi? Grazie

P.S.: non è supportata la notazione `:emoji:`; gli a-capo erano mancanti o errati

2024-05-06 19:18 UTC, Hantex9 commented
> Ci sono diversi errori, il codice corretto è il seguente:
> 
> ```
>   "content": {
>     "subject": "Carta Giovani Nazionale: le novità del mese di Maggio",
>     "markdown": "---\nit:\n    cta_1: \n        text: \"Vai a CGN\"\n        action: \"ioit://CGN_DETAILS\"\nen:\n    cta_1: \n        text: \"See your CGN\"\n        action: \"ioit://CGN_DETAILS\"\n---\nLo sai che su Carta Giovani Nazionale ci sono delle nuove opportunità che possono interessarti?\n\n📌 Sedute di psicoterapia, corsi di francese, ingressi a musei e parco divertimenti, servizi e utenze per la casa.  \nScopri le novità del mese, le riconosci dal simbolo 🔔\n\nSeguici sui social per avere tutti i dettagli  \nInstagram - [Le novità del mese](https://www.instagram.com/p/C6f8KwSo4xG/?igsh=bDRrbXVhb2E2ajlk)  \nFacebook - [Le novità del mese](https://www.facebook.com/share/p/aDtKfRHYjMFmaUjh/?mibextid=WC7FNe)"
>     }
> ```
> 
> Potete sistemarlo incollandoci esattamente questo e avvertirmi? Grazie
> 
> P.S.: non è supportata la notazione `:emoji:`; gli a-capo erano mancanti o errati

Inserito quanto indicato: f3b0e7f7efeeb8840320a4aa834939169cd78e03

2024-05-08 09:23 UTC, lucacavallaro approved these changes

2024-05-08 09:29 UTC, merged

2024-05-08 09:35 UTC, angelo-fiorillo approved these changes
Tutto OK, questo è il risultato:
![image](https://github.com/pagopa/io-bulk-message/assets/133282144/3d957201-5846-4126-b693-ec13b60aae39)
La CTA in fondo porta alla rotta interna `ioit://CGN_DETAILS`, raggiungibile solo dai titolari della Carta.